// Realistic stored state in the exact shape Juniper 0.3.0-rc.32 persisted.
//
// rc.32 settings had no contrast, font, layout, or default-assistant fields,
// stored `reducedMotion` as a boolean, and allowed only two densities. Tests
// load this through the same normalisation path the app uses on upgrade.

const capabilities = {
  chat: 'supported',
  text: 'supported',
  streaming: 'supported',
  systemPrompt: 'supported',
  tools: 'supported',
  parallelTools: 'unknown',
  thinking: 'supported',
  structuredOutput: 'unknown',
  images: 'unknown',
  embeddings: 'unknown',
  generationParameters: ['temperature', 'topP', 'maxOutput'],
}

const DEFAULT_PROMPT = 'You are Juniper, a capable and helpful personal AI.'

export function rc32StoredState() {
  return {
    assistants: [
      {
        id: 'assistant-juniper',
        schemaVersion: 2,
        name: 'Juniper',
        description: 'A warm, practical personal assistant.',
        avatar: '✦',
        accent: '#32CD32',
        modelProfileId: 'ollama-local:qwen3:8b',
        systemPrompt: DEFAULT_PROMPT,
        personality: {
          warmth: 78,
          directness: 72,
          playfulness: 32,
          detail: 52,
          creativity: 48,
          formality: 34,
        },
        responseLength: 'balanced',
        generation: { temperature: 0.7, topP: 0.9, maxOutput: 2048, thinking: 'auto' },
        toolPolicy: 'ask',
        memoryPolicy: 'curated',
        welcomeMessage: 'Hey, I’m Juniper. What are we figuring out today?',
        suggestedPrompts: ['Help me plan my week', 'Explain something clearly'],
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-09-10T09:00:00.000Z',
      },
      {
        id: 'assistant-coder',
        schemaVersion: 2,
        name: 'Rowan',
        description: 'Terse code reviewer.',
        avatar: 'R',
        accent: '#3B82F6',
        modelProfileId: 'remote-openai:gpt-remote',
        systemPrompt: 'Review code tersely.',
        personality: {
          warmth: 30,
          directness: 95,
          playfulness: 10,
          detail: 70,
          creativity: 20,
          formality: 60,
        },
        responseLength: 'concise',
        generation: { temperature: 0.2, maxOutput: 1024, thinking: 'off' },
        toolPolicy: 'safe-automatic',
        memoryPolicy: 'off',
        welcomeMessage: 'Paste the diff.',
        suggestedPrompts: [],
        createdAt: '2026-09-01T00:00:00.000Z',
        updatedAt: '2026-09-01T00:00:00.000Z',
      },
    ],
    models: [
      {
        id: 'ollama-local:qwen3:8b',
        providerId: 'ollama-local',
        modelId: 'qwen3:8b',
        displayName: 'qwen3:8b',
        locality: 'local',
        executionLocation: 'on-device',
        compatibilityStatus: 'chat-compatible',
        status: 'ready',
        capabilities,
        description: 'Discovered from Ollama on this machine.',
        fileSizeBytes: 5_225_388_164,
        contextLength: 40960,
      },
      {
        id: 'remote-openai:gpt-remote',
        providerId: 'remote-openai',
        modelId: 'gpt-remote',
        displayName: 'Hosted reviewer model',
        locality: 'remote',
        executionLocation: 'remote',
        compatibilityStatus: 'chat-compatible',
        status: 'ready',
        capabilities,
        description: 'Discovered from a remote endpoint.',
      },
      {
        id: 'ollama-local:removed-model',
        providerId: 'ollama-local',
        modelId: 'removed-model',
        displayName: 'removed-model',
        locality: 'local',
        executionLocation: 'on-device',
        compatibilityStatus: 'unknown',
        status: 'not-found',
        capabilities,
        description: 'No longer installed.',
      },
    ],
    providers: [
      {
        id: 'juniper-local',
        name: 'Juniper on this device',
        kind: 'juniper-local',
        baseUrl: 'http://127.0.0.1',
        locality: 'local',
        transportLocation: 'on-device',
        enabled: true,
        status: 'unknown',
        capabilities,
      },
      {
        id: 'ollama-local',
        name: 'Ollama on this machine',
        kind: 'ollama',
        baseUrl: 'http://127.0.0.1:11434',
        locality: 'local',
        transportLocation: 'on-device',
        enabled: true,
        status: 'connected',
        capabilities,
      },
      {
        id: 'remote-openai',
        name: 'Hosted endpoint',
        kind: 'openai-compatible',
        baseUrl: 'https://api.example.com/v1',
        locality: 'remote',
        transportLocation: 'remote',
        apiKeyRef: 'credential-abc',
        enabled: true,
        status: 'unknown',
        capabilities,
      },
    ],
    conversations: [
      {
        id: 'chat-plan',
        title: 'Plan the garden beds',
        assistantId: 'assistant-juniper',
        createdAt: '2026-09-16T08:00:00.000Z',
        updatedAt: '2026-09-16T08:05:00.000Z',
        messages: [
          {
            id: 'm1',
            conversationId: 'chat-plan',
            role: 'user',
            parts: [{ id: 'p1', type: 'text', text: 'How should I lay out three raised beds?' }],
            createdAt: '2026-09-16T08:00:00.000Z',
          },
          {
            id: 'm2',
            conversationId: 'chat-plan',
            role: 'assistant',
            modelId: 'qwen3:8b',
            providerId: 'ollama-local',
            usage: { inputTokens: 812, outputTokens: 214, totalTokens: 1026 },
            parts: [
              {
                id: 'p2',
                type: 'text',
                text: '## A simple layout\n\nRun the beds **north to south** so each gets even light.\n\n- Leave `60 cm` paths\n- Put tall crops on the north end\n\n```text\n[bed 1] [bed 2] [bed 3]\n```',
              },
              { id: 'p3', type: 'reasoning', text: 'Consider sun direction and path width.' },
              {
                id: 'p4',
                type: 'tool-call',
                name: 'unit.convert',
                status: 'unavailable',
                metadata: { callId: 'call-1', arguments: '{"value":2,"from":"ft","to":"cm"}' },
              },
              {
                id: 'p5',
                type: 'tool-result',
                name: 'unit.convert',
                status: 'success',
                text: '{"value":60.96,"unit":"cm"}',
                metadata: { callId: 'call-1' },
              },
            ],
            createdAt: '2026-09-16T08:00:05.000Z',
          },
        ],
      },
      {
        id: 'chat-review',
        title: 'Review the storage patch',
        assistantId: 'assistant-coder',
        createdAt: '2026-09-12T10:00:00.000Z',
        updatedAt: '2026-09-12T10:01:00.000Z',
        modelProfileId: 'ollama-local:removed-model',
        messages: [
          {
            id: 'r1',
            conversationId: 'chat-review',
            role: 'user',
            parts: [{ id: 'rp1', type: 'text', text: 'Is this migration safe?' }],
            createdAt: '2026-09-12T10:00:00.000Z',
          },
          {
            id: 'r2',
            conversationId: 'chat-review',
            role: 'assistant',
            modelId: 'removed-model',
            providerId: 'ollama-local',
            parts: [
              {
                id: 'rp2',
                type: 'error',
                text: 'The provider stopped responding.',
                metadata: { errorCode: 'PROVIDER_TIMEOUT' },
              },
            ],
            createdAt: '2026-09-12T10:00:30.000Z',
          },
        ],
      },
    ],
    memories: [
      {
        id: 'memory-1',
        content: 'Prefers metric units.',
        source: 'user',
        enabled: true,
        createdAt: '2026-09-01T00:00:00.000Z',
        updatedAt: '2026-09-01T00:00:00.000Z',
      },
    ],
    attachments: [],
    permissions: [
      {
        id: 'grant-1',
        toolName: 'memory.list',
        scope: 'assistant',
        assistantId: 'assistant-juniper',
        createdAt: '2026-09-02T00:00:00.000Z',
        updatedAt: '2026-09-02T00:00:00.000Z',
      },
    ],
    settings: {
      theme: 'dark',
      accent: '#3B82F6',
      fontScale: 1.1,
      density: 'compact',
      reducedMotion: true,
      developerMode: true,
      telemetry: 'off',
      onboardingComplete: true,
    },
    deviceLink: { enabled: false, hosting: false, deviceId: '', peers: [] },
  }
}
